### ISSUE TITLE
Release version with new name

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-heatmap#22]
* Release new version
* Release last version under old name pointing to new name
* Document on the website

**Comment by adamltyson** [comment]
@willGraham01 is there anything I've forgotten in this process following renaming a repo?

**Comment by willGraham01** [comment]
Technically we should release the final version under the old name (to PyPI), before releasing the new version under the new name (to PyPI).

Releasing the new version will require us changing the API key on the automatic deploy, and will mean we can't roll back to the old name to mark as deprecated.

The repo, it turns out, can be renamed whenever since it doesn't contribute to the metadata.

**Comment by adamltyson** [comment]
This repo doesn't have an API secret saved anyway I don't think. I'm also not a maintainer of the old PyPI package. I've asked @FedeClaudi to add me, then I can release the final version of `bgheatmaps` which has a warning about the renaming. This is in a branch (https://github.com/brainglobe/brainglobe-heatmap/tree/deprecate) and can be released anytime. Considering this, I guess we can just go ahead and release the first version of `brainglobe-heatmap`?

**Comment by adamltyson** [comment]
[brainglobe-heatmap](https://pypi.org/project/brainglobe-heatmap/) is now released, and the pypi key has been added to the repo for future releases.

**Comment by adamltyson** [comment]
[Final version of bgheatmap has been released](https://pypi.org/project/bgheatmap/0.4.0/)
